from src.pycristoforo.com.pycristoforo import generate_random, setup_shape


def get_shape(key: str):
    """
    This method returns the shape (or shapes) as 'Polygon' or 'MultyPoligon' type
    :param key: country ISO2 code/ISO3 code/name/FIPS code
    :return: the shape as Polygon or Multipolygon
    """
    return setup_shape(key)


def get_envelope(shape):
    """
    It returns the envelope built on top the shape passed as input
    :param shape: Polygon or Multipolygon
    :return: shape envelope
    """
    return shape.envelope


def get_random_geoloc(shape, num: int, key: str):
    """
    It generates 'points' (ex. 1, 5, 10, 1000) random latitude-longitude pairs (uniform generated).
    :param shape: shape in which you want to fit your geolocations . Polygon and MultiPolygon are the only shapes accepted
    :param num: how many random latitude-longitude pairs do you want to generate
    :param key: country ISO2 code/ISO3 code/name/FIPS code
    :return: list of features (geojson) containing the random points generated by the method
    """
    return generate_random(shape, num, key)


